### PR TITLE
allow empty arrays in rethink tables

### PR DESCRIPTION
**Pull request by nightshade427**

### CODE REVIEW

**Comment by orthecreedence** [comment]
I'm fine with the list detection in to-array, but casting `nil` to an array in cmd-arg might mess some things up. A lot of my apps assume nil => null, and use #() for empty array. It's kind of arbitrary since nil is false, null, and [] in lisp but that's the initial direction things took with the library and a lot has been built around that.

I'm fine with revisiting this (perhaps a `*nil-is-empty-array*` flag that defaults to false), but let's leave it out of this PR.

**Comment by nightshade427** [comment]
Im using the jonathan values in most of my projects now.

1. :null in lisp => for null in rethinkdb tables, when reading jonathan converts to :null, I use as :null or if needed I convert :null to nil when needed

2. nil in lisp => for [] in rethink, when reading jonathan converts [] to nil so no need to convert as nil is already empty list 

3. :false in lisp => for false in rethink, when reading jonathan converts to :false, I uses as :false or if needed I convert :false to nil when needed

Works pretty well.

Otherwise there is no way to store [] in rethink as all are converted to nil. I have other apps that read the same rethink data and [] is more semantic than nil when something is supposed to be an array.

if that makes sense? Thoughts?

**Comment by nightshade427** [comment]
We can close this request for now and revisit later if you want. Just thought I would share it as it seems to work well and gives me lots of flexibility.

In the meantime I can leave the code in my fork to handle the different false, [], null, values and merge from upstream when needed.

Let me know :)

**Comment by orthecreedence** [comment]
All this makes sense, and it sounds like the best move. I opened a new issue: https://github.com/orthecreedence/cl-rethinkdb/issues/44

For now, I can't accept the pull unless the reql/commands.lisp file is reverted (but still appreciate your work here!)

**Comment by nightshade427** [comment]
Yeah no worries, I think that is a good way to go (the opened issue above). We can close this out our you can leave it open for reference of you want. Whichever is best for you :)

**Comment by nightshade427** [comment]
Maybe I will try and do https://github.com/orthecreedence/cl-rethinkdb/issues/44 and make another pull request :)

**Comment by orthecreedence** [comment]
Note that I partially merged this for now (I still want your to-array list fix)

**Comment by nightshade427** [comment]
Ahh, okay great! Thbaks for the heads up :)

**Pull request closed without merging**
